<MainScreen>:
    BoxLayout:
        orientation: "vertical"
        spacing: 5
        padding: 5

        # Header always visible in MainScreen
        ScreenHeader:
            id: screen_header
            title: "Main Menu"
            show_back: True
            size_hint_y: 0.1

        # StackWidget to handle screens
        StackWidget:
            id: stack_widget
            size_hint_y: 0.9
