<MainScreen>:
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 10

        Image:
            source: "assets/logo.png"
            size_hint_y: 0.3

        Button:
            text: "Detections"
            on_release: app.root.current = "detection"

        Button:
            text: "Calibrations"
            on_release: app.root.current = "calibration"

        Button:
            text: "Analyzer"
            on_release: app.root.current = "analyzer"
