<StackWidget>:
    ScreenManager:
        id: stack_manager

        OptionScreen:
            name: "option"

        DetectionScreen:
            name: "detection"

        CalibrationScreen:
            name: "calibration"

        AnalyzerScreen:
            name: "analyzer"

        StatusScreen:
            name: "status"

        SettingScreen:
            name: "setting"
        
        
